version: "3"
services:
  redis:
    image: redis
    user: "redis:redis"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline
    user: "postgres:postgres"
  s3:
    image: lphoward/fake-s3
    ports:
      - "127.0.0.1:4569:4569"
    volumes:
      - ./fakes3:/fakes3_root
